#!/bin/bash
set -e

# Create the yangcache directory and set permissions
mkdir -p /usr/share/yangcache
mkdir -p /var/cache/jetty9/webapps/yangcache
chown jetty:jetty /var/cache/jetty9/webapps/yangcache
chmod 755 /var/cache/jetty9/webapps/yangcache

# Copy files
cp -r /usr/share/excelfore-yang-explorer/explorer/target/*.war /var/lib/jetty9/webapps/ROOT.war
cp -r /usr/share/excelfore-yang-explorer/anc/target/site/apidocs /var/lib/jetty9/webapps/

# Remove existing directory if needed
if [ -d "/var/lib/jetty9/webapps/root" ]; then
    rm -rf /var/lib/jetty9/webapps/root
fi

# Create the configuration file
echo "YANGCACHE_DIR=/var/cache/jetty9/webapps/yangcache" | tee /etc/excelforeyangexplorer.conf >/dev/null
chmod 644 /etc/excelforeyangexplorer.conf

# Check if the line already exists in the file
JETTY_SERVICE_FILE="/usr/share/jetty9/bin/jetty.service"
if ! grep -q 'ReadWritePaths=/var/lib/jetty9/ /var/cache/jetty9/' "$JETTY_SERVICE_FILE"; then
    # If the line does not exist, add it
    sed -i '/^\[Service\]/a ReadWritePaths=/var/lib/jetty9/ /var/cache/jetty9/' "$JETTY_SERVICE_FILE"
fi

# Jetty9 Service Update
sed -i '/^ReadWritePaths=.*\/var\/lib\/jetty9\/.*$/ { /\/var\/cache\/jetty9/! s/.*/&,\/var\/cache\/jetty9/ } ; /^# Security/ { N; s/\n\(.*\)\(ReadWritePaths=.*\/var\/lib\/jetty9\/.*\)/\n\1\2\n\1ReadWritePaths=\/var\/lib\/jetty9\/ \/var\/cache\/jetty9/ }' /usr/lib/systemd/system/jetty9.service

# Reload systemd daemon
systemctl daemon-reload

exit 0

